# Generated by Django 3.1.4 on 2020-12-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=50)),
                ('Course_code', models.CharField(max_length=10)),
            ],
        ),
    ]
