# Generated by Django 3.1.4 on 2020-12-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201205_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Does_it_have_Prerequisite',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Taken',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_it_required',
        ),
    ]
