# Generated by Django 3.1.4 on 2020-12-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201205_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='level',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='pre_reqisite',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='semester',
        ),
    ]
