# Generated by Django 3.1.2 on 2020-12-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201205_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Course_code',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Course_name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Does_it_have_Prerequisite',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Taken',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_it_required',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='level',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='pre_reqisite',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='semester',
        ),
    ]
