# Generated by Django 3.1.2 on 2020-12-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201215_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Course_code',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='courses',
            name='Course_name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='courses',
            name='Does_it_have_Prerequisite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='Taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_it_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='pre_reqisite',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], default='Fall', max_length=50),
        ),
    ]
