# Generated by Django 3.1.2 on 2020-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201215_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_code',
            field=models.CharField(default='course code', max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Course_name',
            field=models.CharField(default='course name', max_length=50),
        ),
    ]
