# Generated by Django 3.1.2 on 2020-12-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(default=1.0),
        ),
    ]
